# mask_ratios are a range [start, end) with step size `step`
# by area must be False for the completeness test
mask_ratios:
    start: 0.10
    end: 1.0
    step: 0.10

imputation:
    type: ROAD
    smap_mask_mode: morf
    by_area: false
