data_type: ImageFolder

img_norm_cfg:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

data:
    data_loader:
        batch_size: 128
        shuffle: false
        num_workers: 8
    test:
        type: ImageFolder
        img_root: data/cifar100/attribution/
        pipeline:
            - type: SmallestMaxSize
              max_size: 256
            - type: CenterCrop
              height: 224
              width: 224
            - type: Normalize
              mean: 0.485
              std: 0.229
            - type: ToTensorV2
        smap_root: data/cifar100/smaps/gradcam/
        cls_to_ind_file: data/cifar100/cifar100_cls_to_ind.json
